name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: run
      uses: cedrickring/golang-action@1.3.0
    - name: Run terratest
      run: |
        curl "https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip" -o tmp/terraform.zip && \
        unzip terraform.zip -d /usr/local/bin && \
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh && \
        cd test && \
        dep ensure -v && \
        go test -timeout 90m .
